{{- if .Values.starrocksCluster.enabledCn }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "starrockscluster.cn.name" }}-cm
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "kube-starrocks.name" . }}
    app: "cn"
data:
{{ include "starrockscluster.cn.config" . | indent 2 }}

{{- end }}
