apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "starrockscluster.fe.name" . }}-cm
  namespace: {{ template "starrockscluster.namespace" . }}
  labels:
    cluster: {{ template "kube-starrocks.name" . }}
    app: "fe"
data:
{{ include "starrockscluster.fe.config" . | indent 2 }}