# Default values for kube-starrocks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  rbac:
    create: true

# deploy operator in special namespace.
nameOverride: ""
starrocksOperator:
  # provide a name for operator deployment.
  enabled: true
  serviceAccountName: ""
  namespaceOverride: ""
  image:
    registry: hub.docker
    repository: starrocks/centos-operator
    tag: v1.0
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi


# deploy a starrocks cluster
starrocksCluster:
  # Provide a name for starprocks cluster
  name: ""
  ## service account for fe and be to use.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  serviceAccount: ""
  namespace: ""
  ## annotations for starrocks cluster
  annotations: {}
  labels:
    object: test
  ## specify the cn deploy or not.
  enabledCn: true

##  fe spec to deploy fe components.
starrocksFESpec:
  ## Number of replicas to deploy for a fe statefulset.
  replicas: 1
  image:
    registry: hub.docker
    repository: starrocks/fe
    tag: 2.4.1
  ## specify the service name and port config.
  serviceName: ""
  # resource config for fe components.
  resources:
    requests:
      cpu: 4
      memory: 4Gi
    limits:
      cpu: 8
      memory: 16Gi

  # fe storageSpec for persistent meta data.
  storageSpec: {}
  ## specify storageclass name and request size.
  # name: fe-meta-storage
  # storageSize: 10Gi
  # TODO:set default configmapName
  configMapName: ""
  config: |
    LOG_DIR = ${STARROCKS_HOME}/log
    DATE = "$(date +%Y%m%d-%H%M%S)"
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:${LOG_DIR}/fe.gc.log.$DATE"
    JAVA_OPTS_FOR_JDK_9="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 -Xlog:gc*:${LOG_DIR}/fe.gc.log.$DATE:time"
    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010
    mysql_service_nio_enabled = true   
    sys_log_level = INFO

# spec for compute node, compute node provide compute function.
starrocksCnSpec:
  image:
    registry: hub.docker
    repository: starrocks/cn
    tag: 2.4.1
  autoScalingPolicy:
    maxReplicas: 10
    minReplicas: 1
    hpaPolicy:
      metrics:
        - type: Resource
          resource:
            name: memory
            target:
              averageUtilization: 30
              type: Utilization
        - type: Resource
          resource:
            name: cpu
            target:
              averageUtilization: 30
              type: Utilization
      behavior:
        scaleUp:
          policies:
            - type: Pods
              value: 1
              periodSeconds: 10
        scaleDown:
          selectPolicy: Disabled

  ## define resources requests and limits for cn pods.
  resource:
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 4
      memory: 8Gi
  feServiceName: ""
  config: |
    sys_log_level = INFO
    # ports for admin, web, heartbeat service
    thrift_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060


## spec for component be, be provide storage and compute function.
starrocksBeSpec:
  ## Number of replicas to deploy for a be statefulset.
  replicas: 1
  image:
    registry: hub.docker
    repository: starrocks/be
    tag: 2.4.1
  resource:
    requests:
      cpu: 4
      memory: 4Gi
    limits:
      cpu: 8
      memory: 16Gi

  storageSpec: {}
  ## specify storageclass name and request size.
  # name: fe-meta-storage
  # storageSize: 10Gi
  config: |
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    sys_log_level = INFO
    default_rowset_type = beta
